instance_type: "p3.2xlarge"
compute:
  num_cpus: 8
  memory_gb: 61
  num_gpus: 1
training:
  batch_size: 16
  gradient_accumulation_steps: 2
  fp16: true
  num_workers: 4
  max_length: 1024
  cache_dir: "cache"
model:
  model_type: "bart"
  model_name: "facebook/bart-large"
  dtype: "bfloat16"