instance_type: "p3.2xlarge"

compute:
  num_cpus: 8
  memory_gb: 61
  num_gpus: 1
  cuda_visible_devices: "0"
  torch_num_threads: 4

training:
  batch_size: 16
  gradient_accumulation_steps: 2
  fp16: true
  num_workers: 4
  max_length: 1024
  cache_dir: "cache"

model:
  model_type: "bart"
  model_name: "facebook/bart-large"
  dtype: "bfloat16"

aws:
  region: "us-west-2"
  s3_bucket: "your-model-bucket"
  sagemaker_role_arn: "arn:aws:iam::your-account-id:role/service-role/AmazonSageMaker-ExecutionRole"
  cloudwatch:
    log_group: "/aws/summarization"
    log_stream: "training"

logging:
  level: "INFO"
  log_dir: "./logs"
  tensorboard_dir: "./logs/tensorboard"

monitoring:
  enable_wandb: false
  wandb_project: "summarization"
  wandb_entity: "your-wandb-entity"

security:
  enable_iam_auth: true
  use_aws_ssm: true
  ssm_parameter_path: "/summarization/"

development:
  debug_mode: false
  profile_code: false
  disable_tqdm: false