# Configuration file for the text summarization pipeline.

dataset:
  dataset_name: "cnn_dailymail"
  dataset_version: "3.0.0"
  sample_size: 10
  input_column: "article"
  target_column: "highlights"
  max_input_length: 512
  max_target_length: 128

model:
  model_name: "google-t5/t5-small"
  pretrained_model_name: "facebook/bart-large-cnn"

training:
  batch_size: 16
  learning_rate: 5e-5
  num_epochs: 3

evaluation:
  metrics:
    - "rouge"
    - "bleu"

output:
  output_dir: "./outputs"
  save_model: false
