extends: "../base_config.yaml"

instance_type: "p3.2xlarge"

compute:
  num_cpus: 8
  memory_gb: 64
  num_gpus: 1
  cuda_visible_devices: "0"
  torch_num_threads: 4

model:
  # Override base config
  dtype: "bfloat16"  # GPU optimized
  quantize: false

training:
  batch_size: 32
  num_workers: 4
  dataset_in_memory: false

development:
  enable_gpu_optimizations: true
  cuda_kernels:
    enable: true
    optimize_memory: true
