extends: "../base_config.yaml"

instance_type: "r5.2xlarge"

compute:
  num_cpus: 8
  memory_gb: 64
  num_gpus: 0
  torch_num_threads: 8

model:
  # Override base config
  dtype: "float32"  # CPU optimized
  quantize: true

training:
  batch_size: 16
  num_workers: 6
  dataset_in_memory: true

development:
  enable_cpu_optimizations: true
  parallel_processing:
    enable: true
    num_processes: 6
