extends: "../base_config.yaml"

instance_type: "r5.2xlarge"

# Model configuration
model:
  model_name: "facebook/bart-base"  # Smaller model for CPU
  model_type: "bart"
  max_length: 512
  min_length: 50
  num_beams: 4
  dtype: "float32"  # CPU optimized
  quantize: true    # Enable quantization for CPU

# Dataset configuration
dataset:
  name: "cnn_dailymail"
  version: "3.0.0"
  split: "test"
  sample_size: 1000  # Adjust based on memory constraints
  cache_dir: "cache"

# Compute resources
compute:
  num_cpus: 8
  memory_gb: 64
  num_gpus: 0
  cuda_visible_devices: ""
  torch_num_threads: 8
  use_bfloat16: false  # Disable for CPU
  device: "cpu"
  batch_size: 4  # Smaller batch size for CPU

# AWS specific settings
aws:
  region: "us-west-2"
  s3_bucket: "summarization-models"
  sagemaker_role_arn: "arn:aws:iam::ACCOUNT_ID:role/SageMakerRole"
  cloudwatch:
    enabled: true
    log_group: "/summarization/pretrained"
    log_stream: "r5-instance"

# Optimization settings
optimization:
  fp16: false  # Disable for CPU
  gradient_checkpointing: false
  cpu_offload: false
  quantization:
    enabled: true
    bits: 8
    type: "dynamic"

# Output configuration
output:
  dir: "outputs/r5_runs"
  save_model: true
  save_predictions: true
  metrics:
    rouge: true
    bleu: true
    meteor: true

# Resource management
resources:
  max_memory_gb: 60  # Leave some headroom
  cleanup_cache: true
  optimize_for_cpu: true

# Logging configuration
logging:
  level: "INFO"
  log_dir: "logs"
  cloudwatch_enabled: true
  local_logging: true
  log_format: "json"

# Development settings
development:
  enable_cpu_optimizations: true
  debug: false
  profile_memory: true
  parallel_processing:
    enable: true
    num_processes: 6

# Security settings
security:
  enable_ssl: true
  verify_ssl: true
  use_iam_role: true
